"""
Data models for TMUX Fleet Dashboard
"""

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class HostStatus(str, Enum):
    """Status of a monitored host"""
    ONLINE = "online"
    OFFLINE = "offline"
    DEGRADED = "degraded"


class SessionStatus(str, Enum):
    """Status of a tmux session"""
    ACTIVE = "active"
    LEGACY = "legacy"


class AlertSeverity(str, Enum):
    """Severity level of an alert"""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertType(str, Enum):
    """Types of alerts the system can generate"""
    LEGACY_SESSION = "legacy_session"
    ANCIENT_SESSION = "ancient_session"
    SESSION_HIGH_CPU = "session_high_cpu"
    SESSION_HIGH_MEMORY = "session_high_memory"
    HOST_OFFLINE = "host_offline"
    HOST_HIGH_CPU = "host_high_cpu"
    HOST_HIGH_MEMORY = "host_high_memory"
    GPU_TEMP_WARNING = "gpu_temp_warning"
    GPU_TEMP_CRITICAL = "gpu_temp_critical"
    GPU_MEMORY_HIGH = "gpu_memory_high"


class GPUProcess(BaseModel):
    """A process using GPU resources"""
    pid: int
    name: str
    memory_mb: int


class GPU(BaseModel):
    """NVIDIA GPU metrics"""
    index: int
    name: str
    power_draw_watts: float
    power_limit_watts: float
    memory_used_mb: int
    memory_total_mb: int
    utilization_percent: int
    temperature_c: int
    processes: list[GPUProcess] = Field(default_factory=list)
    
    @property
    def memory_percent(self) -> float:
        if self.memory_total_mb == 0:
            return 0.0
        return (self.memory_used_mb / self.memory_total_mb) * 100
    
    @property
    def power_percent(self) -> float:
        if self.power_limit_watts == 0:
            return 0.0
        return (self.power_draw_watts / self.power_limit_watts) * 100


class Session(BaseModel):
    """A tmux session"""
    id: str  # format: "host:session_name"
    host: str
    name: str
    created: Optional[datetime] = None
    last_activity: Optional[datetime] = None
    attached: bool = False
    window_count: int = 1
    status: SessionStatus = SessionStatus.ACTIVE
    # Resource usage (best effort)
    pids: list[int] = Field(default_factory=list)
    cpu_percent: float = 0.0
    memory_mb: float = 0.0
    gpu_memory_mb: Optional[float] = None
    
    @property
    def age_seconds(self) -> Optional[int]:
        if self.created is None:
            return None
        return int((datetime.utcnow() - self.created).total_seconds())
    
    @property
    def detached_seconds(self) -> Optional[int]:
        if self.last_activity is None or self.attached:
            return None
        return int((datetime.utcnow() - self.last_activity).total_seconds())


class Host(BaseModel):
    """A monitored host with its metrics and sessions"""
    hostname: str
    address: str
    last_seen: Optional[datetime] = None
    status: HostStatus = HostStatus.OFFLINE
    # System metrics
    cpu_percent: float = 0.0
    memory_percent: float = 0.0
    memory_used_mb: int = 0
    memory_total_mb: int = 0
    load_avg: tuple[float, float, float] = (0.0, 0.0, 0.0)
    # GPU metrics
    has_gpu: bool = False
    gpus: list[GPU] = Field(default_factory=list)
    # Sessions
    sessions: list[Session] = Field(default_factory=list)
    # Metadata
    tags: list[str] = Field(default_factory=list)
    error_message: Optional[str] = None
    
    @property
    def session_count(self) -> int:
        return len(self.sessions)
    
    @property
    def active_session_count(self) -> int:
        return sum(1 for s in self.sessions if s.status == SessionStatus.ACTIVE)
    
    @property
    def legacy_session_count(self) -> int:
        return sum(1 for s in self.sessions if s.status == SessionStatus.LEGACY)


class Alert(BaseModel):
    """An alert generated by the monitoring system"""
    id: str
    type: AlertType
    severity: AlertSeverity
    host: str
    session: Optional[str] = None
    message: str
    created: datetime
    acknowledged: bool = False
    acknowledged_at: Optional[datetime] = None
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat() if v else None
        }


class HostConfig(BaseModel):
    """Configuration for a single host"""
    name: str
    address: str
    has_gpu: bool = False
    tags: list[str] = Field(default_factory=list)


class AlertConfig(BaseModel):
    """Alert threshold configuration"""
    enabled: bool = True
    session_cpu_warning: int = 80
    session_memory_mb_warning: int = 2048
    host_cpu_warning: int = 90
    host_memory_warning: int = 90
    gpu_temp_warning: int = 80
    gpu_temp_critical: int = 90
    gpu_memory_warning: int = 90
    gpu_util_info: int = 95


class SSHConfig(BaseModel):
    """SSH connection configuration"""
    user: str = "tmux-dash"
    key_path: str = "/opt/tmux-dashboard/.ssh/id_ed25519"
    timeout: int = 10
    known_hosts_policy: str = "accept"


class Config(BaseModel):
    """Main application configuration"""
    polling_interval_seconds: int = 30
    legacy_threshold_hours: int = 72
    alerts: AlertConfig = Field(default_factory=AlertConfig)
    ssh: SSHConfig = Field(default_factory=SSHConfig)
    hosts: list[HostConfig] = Field(default_factory=list)


# API Response models
class HostsResponse(BaseModel):
    """Response for /api/hosts endpoint"""
    hosts: list[Host]
    timestamp: datetime


class SessionsResponse(BaseModel):
    """Response for /api/sessions endpoint"""
    sessions: list[Session]
    total: int
    active: int
    legacy: int
    timestamp: datetime


class AlertsResponse(BaseModel):
    """Response for /api/alerts endpoint"""
    alerts: list[Alert]
    total: int
    unacknowledged: int
    timestamp: datetime


class StatusResponse(BaseModel):
    """Response for /api/status endpoint"""
    status: str
    version: str
    uptime_seconds: int
    hosts_online: int
    hosts_total: int
    sessions_total: int
    alerts_active: int
    last_poll: Optional[datetime]
